"""empty message

Revision ID: 258b2225585
Revises: 3efce5781331
Create Date: 2023-06-04 22:58:50.813190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258b2225585'
down_revision = '3efce5781331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_analysis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_analysis',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('malicious_count', sa.INTEGER(), nullable=True),
    sa.Column('suspicious_count', sa.INTEGER(), nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=300), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=4), nullable=True),
    sa.Column('resource_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', name='unique_resc_id')
    )
    # ### end Alembic commands ###
