"""update analysis models with last analysis results and stats

Revision ID: c75c7974f057
Revises: 258b2225585
Create Date: 2023-06-05 12:33:46.159184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75c7974f057'
down_revision = '258b2225585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_analysis_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_analysis_stats', sa.JSON(), nullable=True))
        batch_op.drop_column('suspicious_count')
        batch_op.drop_column('malicious_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('malicious_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('suspicious_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('last_analysis_stats')
        batch_op.drop_column('last_analysis_results')

    # ### end Alembic commands ###
